- name: Install essentials
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - git
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - acl
    - virtualenv
    - "openjdk-{{ java_version }}-jdk"

- name: Create a keyring directory
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: Add Docker official GPG key
  become: true
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

- name: Setup repository for Docker
  become: true
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Add Jenkins official GPG key
  become: true
  shell: |
    curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | tee /etc/apt/keyrings/jenkins-keyring.asc > /dev/null
    chmod a+r /etc/apt/keyrings/jenkins-keyring.asc

- name: Setup repository for Jenkins
  become: true
  shell: |
    echo deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | tee /etc/apt/sources.list.d/jenkins.list > /dev/null

- name: Setup Google Chrome Debian package
  become: true
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome-stable_current_amd64.deb
    mode: 0755

- name: Install Google Chrome
  become: true
  apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb

- name: Update all packages
  become: true
  shell: |
    apt update