- hosts: jenkins
  gather_facts: true
  tasks:
    - name: Setup OS
      import_tasks:
        file: tasks/os.yml
    - name: Setup Docker
      import_tasks:
        file: tasks/docker.yml
    - name: Setup Jenkins
      import_tasks:
        file: tasks/jenkins.yml